import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Food Delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className="lg:flex flex-col items-center">
          <div className="xl:w-[1250px] w-full">
            <div className="lg:px-20 md:px-15 sm:px-10 px-4 lg:flex flex-col items-center">
              <Navbar/>
              {children}
            </div>
              <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
